!system echo "Creating View SV_TB_SUPPLY_CHAIN_CUSTOMER_MASTER..."

!set variables_substitution=true
!variables 

CREATE OR REPLACE VIEW SNF_SCA_ANALYTICS_&{ENV}.SUPPLY_CHAIN.SV_TB_SUPPLY_CHAIN_CUSTOMER_MASTER
COPY GRANTS
AS 
SELECT * FROM SNF_SCA_ANALYTICS_&{ENV}.SUPPLY_CHAIN.TB_SUPPLY_CHAIN_CUSTOMER_MASTER;


!system echo "View SV_TB_SUPPLY_CHAIN_CUSTOMER_MASTER created successfully..."