!system echo "Creating View SV_VW_SUPPLY_CHAIN_PAYMENT_ORDERS..."

!set variables_substitution=true
!variables 

CREATE OR REPLACE VIEW SNF_SCA_ANALYTICS_&{ENV}.SUPPLY_CHAIN.SV_VW_SUPPLY_CHAIN_PAYMENT_ORDERS
COPY GRANTS
AS 
SELECT * FROM SNF_SCA_ANALYTICS_&{ENV}.SUPPLY_CHAIN.VW_SUPPLY_CHAIN_PAYMENT_ORDERS;

!system echo "View SV_VW_SUPPLY_CHAIN_PAYMENT_ORDERS created successfully..."