!system echo "Creating View VW_SUPPLY_CHAIN_PAYMENT_ORDERS..."

!set variables_substitution=true
!variables 

CREATE OR REPLACE VIEW SNF_SCA_ANALYTICS_&{ENV}.SUPPLY_CHAIN.VW_SUPPLY_CHAIN_PAYMENT_ORDERS
COPY GRANTS
AS 
WITH PRODUCT_CTE AS (
    SELECT 
        PRODUCT_ID,
        PRODUCT_NAME,
        PRODUCT_CATEGORY
)
SELECT 
    po.ORDER_ID,
    po.ORDER_DATE,
    po.PAYMENT_STATUS,
    po.PAYMENT_AMOUNT,
    od.PRODUCT_ID,
    od.QUANTITY,
    pm.PRODUCT_NAME,
    pm.PRODUCT_CATEGORY
FROM SNF_SCA_ANALYTICS_&{ENV}.SUPPLY_CHAIN.PAYMENT_ORDER po
JOIN SNF_SCA_ANALYTICS_&{ENV}.SUPPLY_CHAIN.ORDER_DETAILS od
    ON po.ORDER_ID = od.ORDER_ID
JOIN PRODUCT_CTE pm
    ON od.PRODUCT_ID = pm.PRODUCT_ID;

!system echo "View VW_SUPPLY_CHAIN_PAYMENT_ORDERS created successfully..."