GRANT SELECT ON VIEW SNF_SCA_ANALYTICS_&{ENV}.SUPPLY_CHAIN.SV_TB_SUPPLY_CHAIN_CUSTOMER_MASTER TO SHARE S_CHEMICALS_BUSINESS_ANALYTICS_&{ENV};  

GRANT SELECT ON VIEW SNF_SCA_ANALYTICS_&{ENV}.SUPPLY_CHAIN.SV_VW_SUPPLY_CHAIN_PAYMENT_ORDERS TO SHARE S_CHEMICALS_BUSINESS_ANALYTICS_&{ENV};  