!set variables_substitution=true
!variables 

CREATE OR REPLACE TABLE SNF_SCA_ANALYTICS_&{ENV}.SUPPLY_CHAIN.TB_SUPPLY_CHAIN_CUSTOMER_MASTER (
    CUSTOMER_ID VARCHAR(10),
    CUSTOMER_NAME VARCHAR(100),
    CUSTOMER_TYPE VARCHAR(10),
    REGION VARCHAR(25),
    EMAIL VARCHAR(100),
    ACCOUNT_CREATION_DATE DATE,
    IS_ACTIVE BOOLEAN
);

!system echo "Table TB_SUPPLY_CHAIN_CUSTOMER_MASTER created successfully..."